### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by OpsCharlie** [fumiyas/samba-virusfilter#7]
Hi,

I could install the module easily following this post:
https://github.com/fumiyas/samba-virusfilter/issues/6

However, Clamav can't access the file

> Scan result: Error: /data/public/virus.txt: Scanner error: lstat() failed: Permission denied.

```
root@ubu1404-fileserver:/data/public# getfacl virus.txt
# file: virus.txt
# owner: ike
# group: ike
user::rw-
group::rw-
group:clamav:rw-
group:se:rw-
mask::rw-
other::---
```

Clamav id:

```
root@ubu1404-fileserver:/data/public# id clamav
uid=108(clamav) gid=113(clamav) groups=113(clamav)
```

**Comment by Charlietje** [comment]
I found the issue:
I needed to disable apparmor

**Comment by fumiyas** [comment]
Please retry with the latest Samba release and  bundled `vfs_virusfilter`(8) module, and report to upstream if you see a problem.
